---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    jenkins_url: "http://{{ ansible_host }}:8080"
    jenkins_admin_username: "admin"

  tasks:

    - name: Check if Jenkins is installed
      shell: dpkg -l | grep jenkins
      register: jenkins_check
      ignore_errors: true

    - name: Install prerequisites (Java)
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
      when: jenkins_check.rc != 0

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
      when: jenkins_check.rc != 0

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb http://pkg.jenkins.io/debian-stable binary/"
        state: present
      when: jenkins_check.rc != 0

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes
      when: jenkins_check.rc != 0

    - name: Enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Wait for Jenkins to be reachable on port 8080
      wait_for:
        port: 8080
        delay: 5
        timeout: 180

    - name: Get Jenkins service status
      shell: systemctl status jenkins.service
      register: jenkins_status
      changed_when: false

    - name: Print Jenkins status
      debug:
        msg: "{{ jenkins_status.stdout_lines }}"

    - name: Create Jenkins user if missing
      user:
        name: jenkins
        state: present

    - name: Add Jenkins to sudoers
      copy:
        dest: /etc/sudoers.d/jenkins
        content: "jenkins ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'

    - name: Validate sudoers file
      command: visudo -cf /etc/sudoers.d/jenkins
      register: sudoers_check
      changed_when: false

    - name: Print sudoers validation
      debug:
        msg: "{{ sudoers_check.stdout }}"

    - name: Wait for Jenkins initial admin password
      wait_for:
        path: /var/lib/jenkins/secrets/initialAdminPassword
        state: present
        delay: 3
        timeout: 120
      register: jenkins_ready
  
    - name: Install apt packages for Ansible & Python support
      apt:
        name:
          - python3-lxml
          - python3-pip
          - ansible
        state: present
        update_cache: yes

    - name: Install python-jenkins via pip with override
      shell: python3 -m pip install --break-system-packages python-jenkins

    - name: Install Ansible collection for Jenkins
      shell: ansible-galaxy collection install community.general
      changed_when: false

    - name: Get Jenkins initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      ignore_errors: true
      when: jenkins_ready is succeeded

    - name: Print Jenkins password
      debug:
        msg: "Jenkins password: {{ jenkins_password.stdout }}"
      when: jenkins_password is defined and jenkins_password.stdout is defined and jenkins_password.stdout != ""

    - name: Save Jenkins password to external file for Terraform output
      copy:
        content: |
          {"jenkins_initial_password": "{{ jenkins_password.stdout }}"}
        dest: /tmp/outjenkins_password.json
      when: jenkins_password is defined and jenkins_password.stdout is defined