apiVersion: apps/v1
kind: Deployment
metadata:
  name: dugma-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dugma
  template:
    metadata:
      labels:
        app: dugma
    spec:
      containers:
        - name: dugma
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.flask.port }}
          env:
            - name: DATABASE_TYPE
              value: "MONGO"
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/"
            - name: MONGO_DB_NAME
              value: "{{ .Values.mongo.db_name }}"
