apiVersion: v1
kind: Service
metadata:
  name: dugma-service
spec:
  type: LoadBalancer
  selector:
    app: dugma
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.flask.port }}
