apiVersion: v1
kind: Service
metadata:
  name: dugma-app-service
spec:
  type: LoadBalancer
  selector:
    app: dugma  # This matches the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.flask.port }}  # Uses the port from values.yaml (5052)
